on: push
name: Deploy to sftp
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.server }}
        remote-user: ${{ secrets.username }}
        private-ssh-key: ${{ secrets.ssh_key }}
        destination-path: applications/yrvguuwjba/public_html/wp-content/plugins/
        